# Generated by Django 4.2.10 on 2024-03-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_post_created_at_alter_post_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeimage",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="home.place",
            ),
        ),
    ]
