# Generated by Django 4.2.10 on 2024-03-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_postimage_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventimage",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="home.event",
            ),
        ),
    ]
