# Generated by Django 4.2.10 on 2024-03-24 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0007_alter_eventimage_event"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="like",),
        migrations.RemoveField(model_name="postcomment", name="like",),
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.ManyToManyField(
                default=0, related_name="like_post", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="postcomment",
            name="like",
            field=models.ManyToManyField(
                default=0, related_name="like_comment", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
