# Generated by Django 4.2.10 on 2024-04-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_remove_post_like_remove_postcomment_like_post_like_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="home.postcomment",
            ),
        ),
    ]
