# Generated by Django 4.2.10 on 2024-04-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_postcomment_parent_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postcomment", options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="postcomment", old_name="parent_comment", new_name="parent",
        ),
    ]
