# Generated by Django 4.2.10 on 2024-04-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_postcomment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="postcomment", name="parent",),
        migrations.AlterField(
            model_name="postcomment",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="home.post",
            ),
        ),
    ]
