# Generated by Django 4.2.10 on 2024-04-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_likedreply_reply_likedreply_reply_likedreply_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="RyplyImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(blank=True, upload_to="ryply_images")),
                (
                    "ryply",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.reply",
                    ),
                ),
            ],
        ),
    ]
