# Generated by Django 4.2.10 on 2024-05-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_ryplyimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ryplyimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="post_images"),
        ),
    ]
