# Generated by Django 4.2.10 on 2024-05-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_ryplyimage_image"),
    ]

    operations = [
        migrations.RenameModel(old_name="RyplyImage", new_name="ReplyImage",),
        migrations.RenameField(
            model_name="replyimage", old_name="ryply", new_name="reply",
        ),
    ]
