# Generated by Django 4.2.10 on 2024-05-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_likedcomment_alter_postcomment_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="parent_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="home.reply",
            ),
        ),
    ]
