# Generated by Django 4.2.10 on 2024-05-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_reply_parent_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="home.postcomment",
            ),
        ),
    ]
