# Generated by Django 4.2.10 on 2024-05-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_reply_parent_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply", name="level", field=models.IntegerField(default=1),
        ),
    ]
