# Generated by Django 4.2.10 on 2024-05-15 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0020_reply_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="follower",
            field=models.ManyToManyField(
                related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
