# Generated by Django 4.2.10 on 2024-05-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_profile_follower"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="follower",),
        migrations.AddField(
            model_name="profile",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="home.profile"
            ),
        ),
    ]
