# Generated by Django 4.2.10 on 2024-05-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_remove_profile_follower_profile_follows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
