# Generated by Django 4.2.10 on 2024-05-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_eventmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replyimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="reply_images/"),
        ),
    ]
