# Generated by Django 4.2.10 on 2024-05-21 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_alter_replyimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="parent_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nested_replies",
                to="home.reply",
            ),
        ),
    ]
