# Generated by Django 4.2.7 on 2024-02-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_likepost_post_image_alter_post_id_alter_post_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
